apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../secrets/encrypted/sealed-secrets-crd.yaml
  - helmrepositories.yaml
  - namespaces.yaml
  - ../../flux/infra/kustomization.yaml
  - ../../flux/apps/kustomization.yaml
