---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: firecrawl-api-key
  namespace: jon-agent
spec:
  encryptedData:
    FIRECRAWL_API_KEY: AgA7CQtoei5zE8NLeYa+OmKUTapLZRuLir+KpvoWwkgYGVQji6m/rJwXxtHIF20P0JvEbPUDnPlTnhSFY8iMPSwqjQA8EotLrT4GIm7hIpIS4OBfm0zBarA+THXiF/hpmWJDB97wM+gjlNg5PTmm5YieLumUq/6qJEx0vOoowONhLOD2+3RLSeR8aHnZ+bA2atuurTgjLMy9jFdjXZzR8JZllSxLBb2WtVosCPzYjXK8vq2yxlryOdR49I0QIhf1vW4PauJ3gWA9JVgdB8HqS4tg4mhhU8mtVsu87JoaYE6a/T6XdxZgC/tiwCjzmvQGfRMaYLZYvBSQK56hC6SAGMcWyAVlsSHOggGlXnMdw/KVw7FTxrdxSn9XVxZtOR8PXd0K8iaBwU6iiHr57ZnSSy+chFhLZILGY26h9K9menJfQ6MgbAE9X2qg/3C5jT5m/jaY6/yMKnfEc0zAnguEG9BfjqOdTp2AoB3D8zpRSDZPuBCxbk1Wtu2q/XT06iS4zbTAHkdJEg6lEs7i8d/FuTb1OoDHUcQRp+oGXUi68ivFvRsccYGCq9J3G9lkCFMf8iIo4IGfNz6l/AEpmAFtPOr/HWu3OD9Xau90NHHvGonc9DtH4MWWpXbjA6XYSqf2/2PGzQGWl7BXSTcJU11mDBO1vKBn9ZllD42TZKanHJ3albQZMgU0iVM6sbrE3TEc95fBtpSz1aC+p6bmBRuymR0ayLx2nyMlxs4Npur+G96RoVEfGw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: firecrawl-api-key
      namespace: jon-agent
    type: Opaque
