---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: hermes-jon-desktop-secrets
  namespace: jon-agent
spec:
  encryptedData:
    HERMES_DASHBOARD_SESSION_TOKEN: AgBImsDA220SvGQXpAKeZat/WRPgPcBmK5G6Y+QzuuR5VPfFWjAA90h2QoW7kAITDkR08PHioRxKif6ZC8bx3EJs+XvVqje0cy5w8FymDXPqA7zC5sFVKDi/cXOJi9N4EfLrBFO4IF/wPnvf+4p0wZeFLrJvHO5jk9jEXUpj/axxwKKIC9i9M+gicYjarheldf0s0bPFS2HrnA372+2XJESzPEH9rRICzr1czI9d35Q8AldgM5EqVI6B3eSbjcMEip4K69wzXBJvpsORp34fun6ff9fs3lojwHU3DatrNRZiuboi11BDH/zl2FaWWUgN4UF/yONLH3iabwmbfz/C0Q394VTdLogtNMSQxHl050lmb+C/sN7p9GcwS4D5vO6JxjUQEHBEF2MLEI2Qg0SuahVOdw5GVlBYnG1qe+7UGMlYqnH3cX2MTzcV2T9+EmUURHZZzBNlA4rhjIsS404oxEP+xV4+5Liq6/tAaR/Ezkf8Z4QkXcEs7sZyzxxij5U8tnyYy+3SK9WS53lI7DG9XGH4nBBsMsH5h+4jqyIPPISO7ljZF4xVhIcglYNJ9aieMr76MVs5lMUZr2H4vleBgyZqg6ec9VflozQytqmssMcEFO1bJ2QvPor2gRZ+VAAAWuQp85KLA9CTmG2isGHW7sOWokU/CoDxiUEIeLb6xqJrVP12l3OQbQsJxnF0tXM7VjjyEDPxlEl729qylSX1qgliMowiRy4OEgFaI2tZphwrZspDYbvPpsqZvsvbFg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: hermes-jon-desktop-secrets
      namespace: jon-agent
    type: Opaque
