---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: hermes-discord-secrets
  namespace: jon-agent
spec:
  encryptedData:
    API_SERVER_KEY: AgBQcy+N+UmeMLz3AYgKcTp5lys1t7x2vochzQ2kFyjHtyA7EzxSUZEwrht6ztuDMvLHKoUTY+DZVhq+Rd+ooVAtMbEV3YIV7bqS97m2uxQpqylhCK85K2XMJiSHixmEumhQohHJ9f7tJXWaM73OaWwNECpFi42CvMIksShhtMi++uat+oWWfznZwwzQeY7d5k3zxiX732hc+szewA1m7gmswGESJXxpPPcwPOIFWxIH55GtohjAzTT6Qe+tjEhDYaLoi9eNZ82OkzA9extvIweA19OO9aIZ6Wh4Kc/gPNKK0HMsKnfJ3zk2Pr/serG1CRX7ujCQY5xv/7FpRLpAzVJm99i6CMSY+KKPseD2IGVp3ze1Z1LbwoPHvoM1jbnjlN2IC/IrRG/Rs2XSFSSrV+mjxauE6nWVC5XZV2X46kOLaqKmkEv1AXNHjTOn847bpFkSFrQqzf4ptfoK/tryg1YmqZ50sg1pFWFbe5kb25jTt6h0DeCuM4sweyLIcD1KN/7dVQZhX0IPTCEfbd3DTJiFtDyF/Suwa2qqH9Xg9d3+oHyY7hYfNv3RSl59YORxU/IIO+lxYoJgMO3AescOV8wiPpk8nJfD3dbbUUepOncJ3SKmQUx1ts+u4TmNq44cNXm5wr9dISGDBSjMIB6Y0qDApwKJB60rsCVfW1XaGBBtsKLYtpV82ew+TPmGFKVSthqCXHnSdVCzVtlU6WQ/BeyRCZfVARD5rUcVxLgaF02BMNZezip0/QOT/+bbHA==
    DISCORD_BOT_TOKEN: AgBbA3RHIBoyW/w78afZlpY1ApVqfX4icyAiypyqsoq2dRfFlMrGjBrCgRB9fGdEoyVpOPeYLfkgKGVMfyovN07X3HZcv2oq4LccuKU94EaFqU+iLtZfAs+jvX8vk5vJU1Ji5Xu50YE2KiVhPyam3w6iXv4hf/fLy65qe03H2bfXYmNExgRBcVJbeAWWNzaIYec4YnA/u2MUfOLjt3+gtFBHVxO5zRQq9BH+JaeZEiwGNIgigsQlMj9QgICE05DGVYe6KFd6tC3j+B/J/Utd2Pv1tT9t3IW1WXhM+fFV/NRwoTixjTujmBXxiC+ORGp88Q1/tk4E0rSMavcXSbsbijHBG3qw2f9JAmdpAIgiZNeKhy9UiOAzvYt5mQYwuTMFUwkC0w2vgbDxvDxik3wENuRqxF7GmV60w/Aq5j+VoRkhQoTfH1aMJjyi+1mFRzFYDXc9TG60bn/dYmxQYdjT9aVskFIkM0hFwrQNPWnTvrVw8v3RVwdAslUzSz0q20Gmxf07oef1JocgATfUFU1vxznb0ljtCPicQlIdYN2D3BTV7RjC4/gcaCOXMEmTpq7vJEk2G8FKP8iOa6nLqvUP1hLLxwfB3S7qOuVoTYacBjcJ+i2eSQRbFMxhW3m88jc+RrfDB4ZRxaNVwg1ieFnGHwQmQHbXPvR792SaTui5qViD7vSd6HmZFiZgH8WBAgdYlSMiEDxomsR9TnAgDYCSLjA54SKjQdOngJmLRqv4kueoZhp2l2ZK1b0yiUrHeGJx9IYOQxzKgJwEhfsC36p9O+5tfP0rE6bDIK0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: hermes-discord-secrets
      namespace: jon-agent
    type: Opaque
