---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: hermes-ana-secrets
  namespace: ana-agent
spec:
  encryptedData:
    API_SERVER_KEY: AgASXVYe05dr9b0zaDaHHjNoBfHAm5VatAJWEQJf80fjLB3I91wdPsEK9EeRFVc9uJuN9v8dFCjtkRxk/t/VYokIff5ndtzZ4sguZc63Nqte7YunDpccUxyxtKlxl8wgBIVodIj2g6CPtmiSn+irFudh07Yrr7c+i+MRMynasdJfuY41FzXX94hWSgQ4JGbzKs5J1SEOIpSqyD3YEyhnBxcj0fnXMt85aH1aS2Imj7e+1KnVZ8Kn3U1PLJVnyG1we2uYkNhsn08mhNUMBo3esa+p3IesNYM+f2BDRVKx96iHU5Km3hhxoIhuah1b13sHnlEcpQlXpxtY0yHADVqg6GV9197sqOINX5dd2eY84OTJjIoOwVVLW/OtAEbl1UXdQ1jkdi3Y/0Min9hfJGkuGcybtByKy/J8zyqEvkLSO6fOuFkLZt6eE5yvdnKwDvY62gtAv3BtzTaFYzJzhZ2UZ/JWyllIswghf9wsNaswvVkgyBu0g7u7tWQ6qQDsBqVAvUkI0lFGSFXMh5dz7hqc6dzFfEBOlaAqc5PWdgkV3972rvflEMZu4QbGBeCcSCwAwMt6MxH/9K27YSzwYNMLzk8XD9CyhMKDmrWLAs2yy6MR1alEMTTsw5WMj+G1/7bGgddHmUyV9ir0Fmuq6rv0zbyBAKyFZUmv0peO5RoyWElWiQNJuKXUtgrzPd8v+2Mp0RJo/2qIaU2i+8ctN4naBojGUo1rc8dPb54beL8ZN7Ppq1Q=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: hermes-ana-secrets
      namespace: ana-agent
    type: Opaque
