---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: hermes-webui-password
  namespace: jon-agent
spec:
  encryptedData:
    password: AgAJlRYQVS5dXg+SIIe5aVWO1LKUwMxEN3fOxaahSLaCgVHjBkxdYeMYzFSRP4I2yR7Xth5MiengnnTR1texZgZ6zxpZOfeDEcNz3xQNuFbDmfhCEv4K9Tog75xyXI0W8CMBM1zEyKeWrTyJ6pzVu0MGC+TpMtg1/F9MQ+o95mdb0AlMQ9R3as3TDroG4LxVtlqrT0lkcl4rz+dFTu2+82D5FVdrCx0jEhon3PS+qQKWnxuuf2u5vC/amipZWtxSY/A86mgf00j0PX5oOXoVeS48JGv3qE0i0HgRFi3Hz/Ezi2vCaXzCXBNw8uAnMjAzkwJtoNKLUXBmArgJ+3zqJLwgfl0Lvlhuaf/15SeM5eSR9Tp5YkB0jeZJgneorQ9fI1NVPZihxdXQVW0Zl7OE6L4FsW6F+FGYvWpPO76pab3XF2ywrk8S2lyoHhlGCyLODd7ECablD6eWUQ92Kzs1cnbEIpMtlLcmPo8TMlHXlqJGcUySyvMXFOfq1CJxJ2ma51leDShyxmpNtPlMVan07sLSr53pPx2gz9NAFjSAfFCCE8yFezsc/DjkGa9fCR6jI1HW74BKDeIOsnO/OPSGlHgJcbgIWyo8Iy8o4bXHWAtIy7QsWbmlgr1rjncu1OA8j5dP/I4W536yQ5BJiF2AMYLgofG3pG1lejUdcRYnc1rG9MwIY4CtuzgXMHnw6QS62v0YfLT9Ml8gTOtdHG3z1bv8q824iBnUsLLKAFevPnk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: hermes-webui-password
      namespace: jon-agent
    type: Opaque
