---
apiVersion: v1
kind: Service
metadata:
  name: hermes-hermes-agent-tailscale
  namespace: jon-agent
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/instance: hermes
    app.kubernetes.io/name: hermes-agent
  ports:
    - name: api-server
      port: 8642
      targetPort: 8642
    - name: webui
      port: 8787
      targetPort: 8787
