apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hermes-jon.yaml
  - hermes-jon-tailscale.yaml
  - hermes-ana.yaml
  - open-webui.yaml
  - open-webui-secret.sealedsecret.yaml
  - open-webui-hermes-openai.sealedsecret.yaml
  - hermes-jon-secrets.sealedsecret.yaml
  - monitoring.yaml
