apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hermes-jon.yaml
  - hermes-jon-tailscale.yaml
  - hermes-webui-password.sealedsecret.yaml
  - hermes-webui-workspace-pvc.yaml
  - hermes-ana.yaml
  - open-webui.yaml
  - open-webui-secret.sealedsecret.yaml
  - hermes-jon-secrets.sealedsecret.yaml
  - hermes-jon-desktop-secrets.sealedsecret.yaml
  - hermes-ana-secrets.sealedsecret.yaml
  - monitoring.yaml
