---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-secret
  namespace: open-webui
spec:
  encryptedData:
    WEBUI_SECRET_KEY: AgB5RCO/4EPwi7v7CEdNGR4xVoH1Hmreb/3iHFsOXt4oAXnlOftSDrhRnLRPmvDQqcIN+Ly0j0qk+FCMp5+tAI84mJ8iJQ4a3dhHM8nwn8rKPKXk66D3NPQGdC41Og83KHq1upVT8D/d39pBoqOWdkzvqLPpFA8ZHIUl5dz0B9LyTq0nMnZH7+y7qF6tM3Zaj+3CeTCo5N4syxPC8ySsnsDg/48ijuZhCpCdtDlhMPZ+M2sV5rvcU0RWHQXnd6E73HlNyEcmqPZ00XSv6x4Vwg/iLYM9GWwUjUMPxZ3o4B7jGU1FceMWjnuYibFVA1PUat99/RcflmUlV5ndtqW8mpFzUyxsABpzWfLL6xi1RrSQDZn9f0mxjsVfqPUbVt+fYS3FDsPg9Sy5QyXv376EI+GOuSfREmdlG5R+/TSlZNrcN1VPEu2xgDOJUYPl4y5i7KJuatXlHr4Fxo/PUQElFMlqkpEvpft1kc+Gh4XtboNKlNu4jnjXghOVr6rJ8wRdRGJ4ZYd36+UtFpdVmHYTm2i2H//Bmz6KIUWaSIsSGCm6jmW1cs0seDRzfesqY288X7vN6Zn9Um59uVnFusT0wH0I1NVo4G5GETwlKuJ+UMLVqAHbB42Hlyq15yrQMU2K+mNivFWXvHcwCVbwQ9wYf4yfQTOy4u04P1C/eq4S0jEK3f4YBthT/XQg+a1fsrSNZDdeAhzz7L/hJHFM9ehjuCWU
    api-key: AgCmGJYPrA7NGO5gTrBuUEmVCxGVuN4VuUA5FJMVWhdpl09qSYi+zX/ceprTvBvTDZNRlOs1OYfVPcS+NSqbsXJx6Z2e4j7yXkiOs/O1n1DdTGGH0DWVRnB6MgGwAiUrRDeOt7Rp83qcve5eyYPfpOKpSCufW/3eCrTFgPLH6mqs9MNiXj5qXoQniJluLKaYjmwyIoCHqDKuiBsws/o6Wz1rkcauWP/9aDtbu7vYMtWJ0qCq7FTW7zy8c/jbc+IyikWGx6DgokslQt/bkaO9tfRPu/m7fHZrnflsxFUmd+l9O2vOEIY8ZnpVRUdrAi5PlsdlZgLTrQKpwFHwCprRwLdrKvZI3HsilnwrsL91EmyXyHc4N8t9/0aVBWNy/kXKVbj+29ry7Om4KVl/mDnH242uqJAwg1pF3DR/1YjTD/Bkb8RlPQ3+xNMnlkNW2hmizRRFbyLEMRphi0oFgffKZdkEr4MjnE/+tE4x9+qghbjClwt2sFrEZrseo23ILoMNed4WLM/6t5qeLHbDNPRkmjaRxKS/Wmphpi4fMpbExGZWwFw1DDh0o34z0WD91XkfTMiuz3lDNIqmG+effgH4rY/I0dhlzHJenGrPGwenZ8Qi95mmFUFY2A2XR7dkCtm3IOx32CMWhTNilJAEKhRGSTKdt9flVvaMA1pyqa0ZFnhoHJXEXSi4Nli8ZPs5dDp2V+LqMylNinwxoeyJBAK9S8VdtZ2JuqQUtF+nD2mBA7/kZgZt8w8vizOpr9EE6A==
  template:
    metadata:
      name: open-webui-secret
      namespace: open-webui
    type: Opaque
