---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-secret
  namespace: open-webui
spec:
  encryptedData:
    WEBUI_SECRET_KEY: AgBNBREFxi5XzF/cCYKxoS5MZPDIH168CaY5Zjf1uaMDtBGNQZfGXshIA331UJcJwpV6DsNw7PbC6ruB/QijZZOp+XYk0L125babytDdDSAmCmVFa4vQkaYPoXlinb8xv6Yc9pgz7kDmY8r0Vd0/CViENaFSbSnqTTnTXm5D8SfAfi9Z4eMnyYN+Uca1TP/KlRpTMcMullm30j5v6HxpLpQIBYfEyBxONju2Wap7ij4KC59stVrzgorzHgnYbjZu+cxBAPiK/ACHRZDLdZJqIQwxk15a6wrAotAimAy2fAoh5qlGqRikC2rNRMmJkNs3ehCFWC6CTXJ1woSrc9fi60g87x3Y8kCnSqRZoZpL+u9bt3BPl9PRTsLg/0i9CDdQE36fIk4VUAhVUPNePprxjOW7sTrFAdpkh7LNpk8rdndL9gbRc2H+TZWgspZNMJjep6HozeX3zZIGAaF+GsiEZyZ4viBs0N3HlbVeU1m0UIhCaR0x7zaKnLF7otAZekNfgm3gB5i3AvWnGMmRunb8kKlD8WSKxNTds7wH4Pg65lgJAoHWcFJTXe2Gh4asfv3XmneSMLIh9S0I7iv4yzauQPkbQ/wTTZLGKqb7rNUe3D+pm9ohApvccOywCOpFrxV8tmB+Fli2n+vA/jlsY/LeHGnFfGUGAHFjAJBiRI31SmI5vfOnoEaPbnPQTd7DqnZ1yMVsxX9um8bPayc25w==
    api-key: AgC53jSeuNZ3y8z+HE18N4KBcvOGpde2LWdFu4zHSXZaQt3Lqp/tx1habjE8Rvwayeb43f8ZZXHaHcA3lZUZytRJT2Yp8i4HzFzfcBILilL5hrhAoEaNDOA/DdlTlTMbXKG4VkBYW65TN3X1HkzFBSozEPuLsZZHGoxGDcWSVs+MiH+d8fnPM7MdEmw6gVXQmAlHiWDd2rvY5uw/tIM3HGc9ZtPvy5z1WQb9C+NWDSUGJ5dlNOJHC2+HZJZ8mxIg6Hn2JH108yWK4DB50gc5v0Phcc+Nyvt6vTON1dadcMbCH2qZd5Z8Xk6CMtsbFjjfLIl/FtNh3U6mGnl+NTxewMqcvPz4zE05KEc3ZdgMasnbT+eKCLNiqpp6pPXkdIivr5Hbl824mW5DIe6HtJ2Nygb5laCaMY2/DVERUn6yCuUhlI9d9FEfNGAR0HiItJsEUjOBVubBi2HcokxfvTTnJaDlHFgTPdRT4N9vkUc1rFH95P4PRKOHhcV4hhUOVkvzlqK0qNDcwv3WZw1hjM8F53DEqw0ztVRv9pLf38U/NbPqB2H5VuiT1Eju3p+XV17Y+p/oZj64eOs7ryyiF5QRwAS8p9iwgqteFAU1AQl7FBa9wgXLTYMM20gj5du7WyImP4ATYbBxVcCPQI2oPltgzsa3woI2uZbFnM9F4KxhAcDNIBhLoQQP1BCZQpgEiT63x/v3gaQdVPdQs9kAEETgDWZEvcTv2ErXZ3ow1BA8tDaGfw==
  template:
    metadata:
      name: open-webui-secret
      namespace: open-webui
    type: Opaque
