---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-secret
  namespace: open-webui
spec:
  encryptedData:
    WEBUI_SECRET_KEY: AgBNBREFxi5XzF/cCYKxoS5MZPDIH168CaY5Zjf1uaMDtBGNQZfGXshIA331UJcJwpV6DsNw7PbC6ruB/QijZZOp+XYk0L125babytDdDSAmCmVFa4vQkaYPoXlinb8xv6Yc9pgz7kDmY8r0Vd0/CViENaFSbSnqTTnTXm5D8SfAfi9Z4eMnyYN+Uca1TP/KlRpTMcMullm30j5v6HxpLpQIBYfEyBxONju2Wap7ij4KC59stVrzgorzHgnYbjZu+cxBAPiK/ACHRZDLdZJqIQwxk15a6wrAotAimAy2fAoh5qlGqRikC2rNRMmJkNs3ehCFWC6CTXJ1woSrc9fi60g87x3Y8kCnSqRZoZpL+u9bt3BPl9PRTsLg/0i9CDdQE36fIk4VUAhVUPNePprxjOW7sTrFAdpkh7LNpk8rdndL9gbRc2H+TZWgspZNMJjep6HozeX3zZIGAaF+GsiEZyZ4viBs0N3HlbVeU1m0UIhCaR0x7zaKnLF7otAZekNfgm3gB5i3AvWnGMmRunb8kKlD8WSKxNTds7wH4Pg65lgJAoHWcFJTXe2Gh4asfv3XmneSMLIh9S0I7iv4yzauQPkbQ/wTTZLGKqb7rNUe3D+pm9ohApvccOywCOpFrxV8tmB+Fli2n+vA/jlsY/LeHGnFfGUGAHFjAJBiRI31SmI5vfOnoEaPbnPQTd7DqnZ1yMVsxX9um8bPayc25w==
    api-key: AgAd3gdS9U4kRMXz9eEERaqgKYvUfJv7NR2ucBVkZcOtXHjfjFLbW5r5wAdYDHDMCHB/n8kPGkxKtCIYJKcCW7ewCoTZOuwL9bE30CSwG2jIcXdche2+XgK96ByHm1x5yCUQfvpO3eOaJn0hohYDMMSgtlZpsdBDJouLSkN03DGGx50Nom6VsieI/bj2wY2QPClSeER1J1eU2coDMqDbIWT3HBBJq9tH+lPSSLlTO04qPJB53CqDnVFzHGNwOZ5Oks97N7P6AlyIX3c4oG+dzR2qmKqf/CAl/k5PZvh7o2ZNnUSESmjHxq5nRt7rqg4U3DJ8eeocIF46SZ7JExb5XQGPPdNTMAzeYsYz49lfCTcpOxPD2cFx+zjf04UWceGSJYyIK5xnNGDIiIC7tGtTLLH/epAH/MrF1CsOassLjIITIC5+FtOBoUuU+2ZrCDQFghGohuHnSi97bf0x+kqP3DFvSijZSjBdJDOKKpqIB833tbNyqtvB58ZZtjS1RHjCjMPe8dWnfFDttuBxBbHuUrrg14AMIoX2Ib9GIor8LKOWiyzluzimWz0xguEZJE2I+Xtpny7sEmNIUMZD90ag4Lu1THWkpmRQUybB/AJ+Re8Agb31Qf3waRzYgiKHqhSIMQuCgwEmC0QrcuGYkXvUP7kT7w/M3dxRvS/6ZpL2I932U+RABh42UhVZ/Qabcy956KH3SYc/lMpjV4yvz/SAbpvC5bLZXjqNoEM6rIJ0Iz2ZUsI=
  template:
    metadata:
      name: open-webui-secret
      namespace: open-webui
    type: Opaque
