---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: trading-assistant
spec:
  encryptedData:
    .dockerconfigjson: AgBPTRY7zdmEyL8W8+VjQnhaXh4qyM+yrEvZqtur/n60a3KfxruNWyRaPCrSPEnOtC8YGa2UGErxxuUfTWcDLA1OOSGJA6t/h9GQeGfUaN6vdLxZ3aNAe9j/rCBW2QkO2zGljrYiHjjGQYJXxEtubw43lizmPX0HoDCj7xh6R8VYWkRg7ExXAJ3J6LiqbpuvLNtnM0M8ZFrVwYEbkfy4uIzSVqrLQldDXfoTKtPvjkKyWcYdPk17R01vjk0ziVouX71jNcgBilMtibGcqlEbxcdR2gcX4Ey2zywDwq42hUWs74btiktxAkPGotpQ7W8XgM/e+uHC+PTHqpb3D0JDJFW5ElzPIX3R8U17WMiGU8nV72L2WeIBpMrgPPttO6cBhFPSVvVs/93rdZZum+P7OrJg2HHNjnueVK+ODsrdFR7vDjWsIkVsijSY6TGMCQ1s1R9FilPMDMTIXpy5V03SOXNBrTS1AOzISrSLOeFPxQIfzJT30WTFGYBWH967LSj2RgXdeuOZnJjqdW/2L1bCsdx7imNf5z8iCMtQOePZ52T5kNp5hwp6lfSAUUaNnenpXBnfh3Uc0kqwUG/AfpUE5LaIn8UU7AOWmYh2sggiNK1kTtf9mEsxFvR5eF4xYGKvChj6+nOfYuIX8NV4spRP+1Rn14PII7iB6VaarokmJMS4bXsa6Um1R7odHXdtxUOrsGQyAGij71kJYu8Q3KtJLrOnDBOJnRwwZIJPST6+QssxwBEX7L4LX4q5Q4BLZNV2WRUfOlV269RWCybqSbSrIAm7VNSMKDMtHRQIB88KTNvuzSgnMLnWpihGoOAN/y5eKxAbYQJeX05oUaO78y5vN1K2USzYooSmSpwPWlmJNZiLRaemKeVtbJJX1Zkj6HOmdwIIGYmRj4/BpiNnJNLlsYWhM9SidGUnQwx3bwpooNo0yeZsSA==
  template:
    metadata:
      name: ghcr-pull
      namespace: trading-assistant
    type: kubernetes.io/dockerconfigjson
