{
 "title": "Nodes",
 "time": { "from": "now-9h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (node) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)   ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))   \n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(node) (node_hwmon_temp_celsius{chip=~\"thermal_thermal_zone0|thermal_thermal_zone1\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Percentage of Memory Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(container_memory_working_set_bytes{container!=\"\"}) by (pod)\n      /\n    sum(kube_pod_container_resource_limits{resource=\"memory\"} > 0) by (pod)\n)   ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SDD Temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg by(node) (node_hwmon_temp_celsius{chip=~\"nvme_nvme0\"})",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}